JDK_HOME := ${HOME}/Desktop/tools/jdk-13
JDK_LIBS := ${JDK_HOME}/lib

JAVAFX_HOME := ${HOME}/Desktop/tools/javafx-sdk-13
JAVAFX_LIBS := ${JAVAFX_HOME}/lib

JAVAC     := ${JDK_HOME}/bin/javac
JAVA_EXEC := ${JDK_HOME}/bin/java
JAR_EXEC  := ${JDK_HOME}/bin/jar

PROTO_JAR := /usr/share/java/protobuf-3.6.1.jar

