/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class A64Sim */

#ifndef _Included_A64Sim
#define _Included_A64Sim
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     A64Sim
 * Method:    SimSerialAPI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_A64Sim_SimSerialAPI
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
