  //'setup/a64sim_exceptions.ini'
   exception_enables.Add(0,GENERATION_ERROR,UNEXPECTED_REEXECUTION);
   TraceLogEntry("  # Testbed.Unexpected_Reexecution: Disabled\n");
   exception_enables.Add(0,GENERATION_ERROR,MALFORMED_INSTRUCTION);
   TraceLogEntry("  # Testbed.Malformed_Instruction: Disabled\n");
   exception_enables.Add(0,GENERATION_ERROR,UNEXPECTED_EXCEPTION);
   TraceLogEntry("  # Testbed.Unexpected_Exception: Disabled\n");
   exception_enables.Add(0,ARCH_EXCEPTION,SOFTWARE_STEP);
   TraceLogEntry("  # Exception Enables.SOFTWARE_STEP: Disabled\n");
   exception_enables.Add(0,ARCH_EXCEPTION,MISALIGNED_PC);
   TraceLogEntry("  # Exception Enables.MISALIGNED_PC: Disabled\n");
   exception_enables.Add(0,ARCH_EXCEPTION,INSTRUCTION_ABORT);
   TraceLogEntry("  # Exception Enables.INSTRUCTION_ABORT: Disabled\n");
   exception_enables.Add(0,ARCH_EXCEPTION,BREAKPOINT);
   TraceLogEntry("  # Exception Enables.BREAKPOINT: Disabled\n");
   exception_enables.Add(0,ARCH_EXCEPTION,DEBUG_BREAKPOINT);
   TraceLogEntry("  # Exception Enables.DEBUG_BREAKPOINT: Disabled\n");
   exception_enables.Add(0,ARCH_EXCEPTION,ILLEGAL_EXECUTION_STATE);
   TraceLogEntry("  # Exception Enables.ILLEGAL_EXECUTION_STATE: Disabled\n");
   exception_enables.Add(0,ARCH_EXCEPTION,UNDEFINED_INSTRUCTION);
   TraceLogEntry("  # Exception Enables.UNDEFINED_INSTRUCTION: Disabled\n");
   exception_enables.Add(0,ARCH_EXCEPTION,SMC_UNDEFINED);
   TraceLogEntry("  # Exception Enables.SMC_UNDEFINED: Disabled\n");
   exception_enables.Add(1,ARCH_EXCEPTION,EXCEPTION_GENERATING_INSTRUCTION);
   TraceLogEntry("  # Exception Enables.EXCEPTION_GENERATING_INSTRUCTION: Enabled\n");
   exception_enables.Add(1,ARCH_EXCEPTION,EXCEPTIONS_TO_EL3);
   TraceLogEntry("  # Exception Enables.EXCEPTIONS_TO_EL3: Enabled\n");
   exception_enables.Add(0,ARCH_EXCEPTION,FLOATING_POINT_EXCEPTIONS);
   TraceLogEntry("  # Exception Enables.FLOATING_POINT_EXCEPTIONS: Disabled\n");
   exception_enables.Add(1,ARCH_EXCEPTION,STACK_POINTER_ALIGNMENT);
   TraceLogEntry("  # Exception Enables.STACK_POINTER_ALIGNMENT: Enabled\n");
   exception_enables.Add(0,ARCH_EXCEPTION,DATA_ABORT);
   TraceLogEntry("  # Exception Enables.DATA_ABORT: Disabled\n");
   exception_enables.Add(0,ARCH_EXCEPTION,DEBUG_WATCHPOINT);
   TraceLogEntry("  # Exception Enables.DEBUG_WATCHPOINT: Disabled\n");
   exception_enables.Add(1,ARCH_EXCEPTION,IRQ);
   TraceLogEntry("  # Exception Enables.IRQ: Enabled\n");
