  //'setup/a64sim.ini'
   my_cpu->Pstate.N(0);
   my_cpu->Pstate.Z(0);
   my_cpu->Pstate.C(0);
   my_cpu->Pstate.V(0);
   my_cpu->Pstate.D(0);
   my_cpu->Pstate.A(0);
   my_cpu->Pstate.I(0);
   my_cpu->Pstate.F(0);
   my_cpu->Pstate.SS(0);
   my_cpu->Pstate.IL(0);
   my_cpu->Pstate.EL(3);
   my_cpu->Pstate.nRW(0);
   my_cpu->Pstate.SP(1);
   my_cpu->Pstate.Q(0);
   my_cpu->Pstate.GE(0);
   TraceLogEntry("# WARNING: Pstate.IT NOT supported or is READ-ONLY...\n");
   my_cpu->Pstate.J(0);
   my_cpu->Pstate.T(0);
   my_cpu->Pstate.E(0);
   TraceLogEntry("    # Pstate: 0x%x\n",my_cpu->Pstate.Value());
   my_cpu->SPSR_EL1.Value(0);
   TraceLogEntry("    # SPSR_EL1: 0x%x\n",my_cpu->SPSR_EL1.Value());
   my_cpu->SPSR_EL2.Value(0);
   TraceLogEntry("    # SPSR_EL2: 0x%x\n",my_cpu->SPSR_EL2.Value());
   my_cpu->SPSR_EL3.Value(0);
   TraceLogEntry("    # SPSR_EL3: 0x%x\n",my_cpu->SPSR_EL3.Value());
   my_cpu->SCR_EL3.TWE(0);
   my_cpu->SCR_EL3.TWI(0);
   my_cpu->SCR_EL3.ST(0);
   my_cpu->SCR_EL3.RW(1);
   my_cpu->SCR_EL3.SIF(1);
   my_cpu->SCR_EL3.HCE(0);
   my_cpu->SCR_EL3.SMD(0);
   my_cpu->SCR_EL3.EA(1);
   my_cpu->SCR_EL3.FIQ(1);
   my_cpu->SCR_EL3.IRQ(1);
   my_cpu->SCR_EL3.NS(0);
   TraceLogEntry("    # SCR_EL3: 0x%x\n",my_cpu->SCR_EL3.Value());
   my_cpu->ID_AA64DFR0_EL1.CTX_CMPs(0);
   my_cpu->ID_AA64DFR0_EL1.WRPs(0);
   my_cpu->ID_AA64DFR0_EL1.BRPs(0);
   TraceLogEntry("# WARNING: ID_AA64DFR0_EL1.PMUVer NOT supported or is READ-ONLY...\n");
   TraceLogEntry("# WARNING: ID_AA64DFR0_EL1.TraceVer NOT supported or is READ-ONLY...\n");
   my_cpu->ID_AA64DFR0_EL1.DebugVer(6);
   TraceLogEntry("    # ID_AA64DFR0_EL1: 0x%x\n",my_cpu->ID_AA64DFR0_EL1.Value());
   my_cpu->ID_AA64MMFR0_EL1.TGran4(0);
   my_cpu->ID_AA64MMFR0_EL1.TGran64(0);
   my_cpu->ID_AA64MMFR0_EL1.TGran16(0);
   my_cpu->ID_AA64MMFR0_EL1.BigEndEL0(0);
   my_cpu->ID_AA64MMFR0_EL1.SNSMem(0);
   my_cpu->ID_AA64MMFR0_EL1.BigEnd(0);
   my_cpu->ID_AA64MMFR0_EL1.ASIDBits(2);
   my_cpu->ID_AA64MMFR0_EL1.PARange(0);
   TraceLogEntry("    # ID_AA64MMFR0_EL1: 0x%x\n",my_cpu->ID_AA64MMFR0_EL1.Value());
   my_cpu->ID_AA64PFR0_EL1.GIC(0);
   my_cpu->ID_AA64PFR0_EL1.AdvSIMD(0);
   my_cpu->ID_AA64PFR0_EL1.FP(0xf);
   my_cpu->ID_AA64PFR0_EL1.EL3(1);
   my_cpu->ID_AA64PFR0_EL1.EL2(0);
   my_cpu->ID_AA64PFR0_EL1.EL1(1);
   my_cpu->ID_AA64PFR0_EL1.EL0(1);
   TraceLogEntry("    # ID_AA64PFR0_EL1: 0x%x\n",my_cpu->ID_AA64PFR0_EL1.Value());
   my_cpu->ID_AA64ISAR0_EL1.CRC32(0);
   my_cpu->ID_AA64ISAR0_EL1.SHA2(0);
   my_cpu->ID_AA64ISAR0_EL1.SHA1(0);
   my_cpu->ID_AA64ISAR0_EL1.AES(0);
   TraceLogEntry("    # ID_AA64ISAR0_EL1: 0x%x\n",my_cpu->ID_AA64ISAR0_EL1.Value());
   my_cpu->CPACR_EL1.TTA(0);
   my_cpu->CPACR_EL1.FPEN(3);
   TraceLogEntry("    # CPACR_EL1: 0x%x\n",my_cpu->CPACR_EL1.Value());
   my_cpu->CPTR_EL2.TCPAC(0);
   my_cpu->CPTR_EL2.TTA(0);
   my_cpu->CPTR_EL2.TFP(0);
   TraceLogEntry("    # CPTR_EL2: 0x%x\n",my_cpu->CPTR_EL2.Value());
   my_cpu->CPTR_EL3.TCPAC(0);
   my_cpu->CPTR_EL3.TTA(0);
   my_cpu->CPTR_EL3.TFP(0);
   TraceLogEntry("    # CPTR_EL3: 0x%x\n",my_cpu->CPTR_EL3.Value());
   my_cpu->MIDR_EL1.Implementer(0x99);
   my_cpu->MIDR_EL1.Variant(0);
   my_cpu->MIDR_EL1.Architecture(0xf);
   my_cpu->MIDR_EL1.PartNum(0);
   my_cpu->MIDR_EL1.Revision(0);
   TraceLogEntry("    # MIDR_EL1: 0x%x\n",my_cpu->MIDR_EL1.Value());
   my_cpu->VPIDR_EL2.Implementer(0x99);
   my_cpu->VPIDR_EL2.Variant(0);
   my_cpu->VPIDR_EL2.Architecture(0xf);
   my_cpu->VPIDR_EL2.PartNum(0);
   my_cpu->VPIDR_EL2.Revision(0);
   TraceLogEntry("    # VPIDR_EL2: 0x%x\n",my_cpu->VPIDR_EL2.Value());
   my_cpu->REVIDR_EL1.Value(0);
   TraceLogEntry("    # REVIDR_EL1: 0x%x\n",my_cpu->REVIDR_EL1.Value());
   my_cpu->MPIDR_EL1.Aff3(0);
   my_cpu->MPIDR_EL1.U(0);
   my_cpu->MPIDR_EL1.MT(0);
   my_cpu->MPIDR_EL1.Aff2(0);
   my_cpu->MPIDR_EL1.Aff1(0);
   my_cpu->MPIDR_EL1.Aff0(0);
   my_cpu->SetID(i);
   TraceLogEntry("    # MPIDR_EL1: 0x%x\n",my_cpu->MPIDR_EL1.Value());
   my_cpu->VMPIDR_EL2.Aff3(0);
   my_cpu->VMPIDR_EL2.U(0);
   my_cpu->VMPIDR_EL2.MT(0);
   my_cpu->VMPIDR_EL2.Aff2(0);
   my_cpu->VMPIDR_EL2.Aff1(0);
   my_cpu->VMPIDR_EL2.Aff0(0);
   my_cpu->SetID(i);
   TraceLogEntry("    # VMPIDR_EL2: 0x%x\n",my_cpu->VMPIDR_EL2.Value());
   my_cpu->CTR_EL0.CWG(0);
   my_cpu->CTR_EL0.ERG(0);
   my_cpu->CTR_EL0.DminLine(3);
   my_cpu->CTR_EL0.L1Ip(3);
   my_cpu->CTR_EL0.IminLine(3);
   TraceLogEntry("    # CTR_EL0: 0x%x\n",my_cpu->CTR_EL0.Value());
   my_cpu->DCZID_EL0.DZP(1);
   my_cpu->DCZID_EL0.BS(0);
   TraceLogEntry("    # DCZID_EL0: 0x%x\n",my_cpu->DCZID_EL0.Value());
   my_cpu->RVBAR_EL1.ResetAddress(0);
   TraceLogEntry("    # RVBAR_EL1: 0x%x\n",my_cpu->RVBAR_EL1.Value());
   my_cpu->RVBAR_EL2.ResetAddress(0);
   TraceLogEntry("    # RVBAR_EL2: 0x%x\n",my_cpu->RVBAR_EL2.Value());
   my_cpu->RVBAR_EL3.ResetAddress(0);
  TraceLogEntry("    # RVBAR_EL3: 0x%x\n",my_cpu->RVBAR_EL3.Value());
